# Generated by Django 5.1.4 on 2025-01-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by',
        ),
    ]
