# Generated by Django 5.1.4 on 2025-01-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_bloodrequest_accepted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.doner')),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.bloodrequest')),
            ],
        ),
    ]
